import math 
x=math.radians(30) 
print("sin:30=",math.sin(x))
x=math.radians(30) 
print("cos:30=",math.cos(x))
x=math.radians(30) 
print("tan:30=",math.tan(x))
print()
x=math.radians(60) 
print("sin:60=",math.sin(x))
x=math.radians(60) 
print("cos:60=",math.cos(x))
x=math.radians(60) 
print("tan:60=",math.tan(x))
print()
x=math.radians(90) 
print("sin:90=",math.sin(x))
x=math.radians(90) 
print("cos:90=",math.cos(x))
x=math.radians(90) 
print("tan:90=",math.tan(x))
print()
x=math.radians(120) 
print("sin:120=",math.sin(x))
x=math.radians(120) 
print("cos:120=",math.cos(x))
x=math.radians(120) 
print("tan:120=",math.tan(x))


